/**
 * @author Test Author

 */

export default {
    AUTHENTICATION_FAILED: 1,
    VALIDATION_FAILED: 2,
    NOT_AUTHORIZED: 3,
    UNSUPPORTED: 4,
    NO_SUCH_APP: 5,
    EMAIL_ALREADY_EXISTS: 6,
    VERIFICATION_FAILED: 7,
    ACCOUNT_NOT_VERIFIED: 8,
    NO_PROPOSAL_ID: 9,
    NO_APPOINTMENT_ID: 10,
    CASE_OP_NOT_ALLOWED: 11,
    NO_CASE_ID: 12,
    APPOINTMENT_BAD_REQUEST: 13,
    APPT_WRONG_STATUS: 14,
    NOT_FOUND: 15,
    VIRT_ROOM_EXPIRED: 16,
    NOT_AUTHENTICATED: 17,
    GENERIC: 18
}
