version: '3'
services:
    pg:
        image: postgres:13.7
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test_db
            - POSTGRES_HOST_AUTH_METHOD=trust
            - N=500
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres ']
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - '5432:5432'
        volumes:
            - test_db:/var/lib/postgresql/data/
        networks:
            - backend
    #######################################
    # Test Service
    #######################################
    test-service:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: us-central1-docker.pkg.dev/inet-prod/repository/quality-test-service:1.0.0
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://postgres:@postgres:5432/test_db?schema=public
        ports:
            - '8080:8080'
            - '8081:8081'
        networks:
            - backend
        depends_on:
            - pg
networks:
    backend:
volumes:
    test_db:
